"use client";
import {useCallback,useEffect,useMemo,useState} from 'react';

const API='http://127.0.0.1:4318/api';
type Lesson={course:string;id:string;path:string;phase:string;title:string;state:Record<string,unknown>};
type Decision={checkpoint:number;decision:'continue'|'changes';message?:string;at:string;automatic?:boolean};
type Detail={files:Record<string,string>;state:Record<string,unknown>;videoConfig:Record<string,string>;decisions:Decision[];uploads:{ppt:boolean;opening:boolean;conclusion:boolean}};
type Job={id:string;action:string;status:string;output:string};
const steps=[['brief','Definir a aula','Objetivo, público e escopo'],['direct','Planejar','Direção pedagógica'],['research','Pesquisar','Fontes oficiais e especialistas'],['script','Criar roteiro','Texto falado e segmentos'],['review1','Revisão técnica 1','Parecer independente'],['human1','Sua aprovação 1','Validar o texto antes dos slides'],['slides','Analisar PowerPoint','Upload e leitura visual'],['adapt','Adaptar aos slides','Sincronizar fala e imagem'],['storyboard','Criar storyboard','Cenas, destaques e animações'],['review2','Revisão técnica 2','Conferência após os slides'],['human2','Sua aprovação 2','Validar roteiro visual'],['voice','Preparar voz','Segmentos e pronúncia'],['voiceGenerate','Gerar narração','ElevenLabs'],['timing','Ajustar timing','Duração real do áudio'],['render','Renderizar vídeo','Remotion'],['audiovisual','Revisão audiovisual','Qualidade final']] as const;
const artifactFor:Record<string,string>={brief:'brief',research:'research',script:'script',review1:'review1',slides:'slideAnalysis',adapt:'adaptation',storyboard:'storyboard',review2:'review2',audiovisual:'qa'};
const api=async(path:string,init?:RequestInit)=>{const res=await fetch(API+path,init);const data=await res.json();if(!res.ok)throw new Error(data.error||'Não foi possível concluir');return data};

export default function Home(){
 const [lessons,setLessons]=useState<Lesson[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[active,setActive]=useState('brief');
 const [editor,setEditor]=useState(''),[baseline,setBaseline]=useState(''),[guidance,setGuidance]=useState(''),[nextTopic,setNextTopic]=useState(''),[notice,setNotice]=useState(''),[job,setJob]=useState<Job|null>(null),[creating,setCreating]=useState(false);
 const lesson=useMemo(()=>lessons.find(l=>l.path===selected),[lessons,selected]);
 const dirty=Boolean(artifactFor[active])&&editor!==baseline;
 const busy=job?.status==='running';
 const loadLessons=useCallback(async()=>{try{const data=await api('/lessons');setLessons(data.lessons);if(!selected&&data.lessons[0])setSelected(data.lessons[0].path)}catch(error){setNotice((error as Error).message)}},[selected]);
 const loadDetail=useCallback(async()=>{if(!selected)return;try{const data=await api('/lesson?path='+encodeURIComponent(selected));setDetail(data);setNextTopic(data.videoConfig.nextTopic||'');const key=artifactFor[active];const content=key?data.files[key]||'':'';setEditor(content);setBaseline(content)}catch(error){setNotice((error as Error).message)}},[selected,active]);
 useEffect(()=>{const timer=setTimeout(()=>{void loadLessons()},0);return()=>clearTimeout(timer)},[loadLessons]);
 useEffect(()=>{const timer=setTimeout(()=>{void loadDetail()},0);return()=>clearTimeout(timer)},[loadDetail]);
 useEffect(()=>{if(!job||job.status!=='running')return;const timer=setInterval(async()=>{try{const data=await api('/jobs/'+job.id);setJob(data);if(data.status!=='running'){clearInterval(timer);await loadDetail();await loadLessons();setNotice(data.status==='done'?'Etapa concluída. Revise o resultado antes de continuar.':'A etapa terminou com erro. Abra os detalhes para verificar.')}}catch(error){clearInterval(timer);setNotice((error as Error).message)}},1500);return()=>clearInterval(timer)},[job,loadDetail,loadLessons]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 const confirmDiscard=()=>!dirty||window.confirm('Existem alterações não salvas. Deseja descartá-las?');
 const choose=(id:string)=>{if(!confirmDiscard())return;setActive(id);setGuidance('');setNotice('')};
 const chooseLesson=(value:string)=>{if(!confirmDiscard())return;setSelected(value);setActive('brief');setGuidance('');setNotice('')};
 const run=async(action=active)=>{if(!selected||busy)return;if(dirty){setNotice('Salve suas alterações humanas antes de chamar o agente.');return}try{if(action==='render')await api('/video-config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessonPath:selected,nextTopic})});const data=await api('/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,lessonPath:selected,input:guidance})});setJob(data);setGuidance('');setNotice('Etapa iniciada. Você pode acompanhar o andamento abaixo.')}catch(error){setNotice((error as Error).message)}};
 const save=async()=>{const artifact=artifactFor[active];if(!artifact||!selected)return;try{const result=await api('/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessonPath:selected,artifact,content:editor,note:guidance||'Revisão humana pela interface'})});setBaseline(editor);setGuidance('');setNotice(result.changed?'Alteração humana salva como versão oficial. Uma aprovação anterior desta fase, se existia, foi invalidada para nova conferência.':'Nenhuma mudança no texto para salvar.');await loadDetail()}catch(error){setNotice((error as Error).message)}};
 const upload=async(kind:string,file?:File)=>{if(!file||!selected||busy)return;setNotice(`Enviando ${file.name}...`);try{await api('/upload',{method:'POST',headers:{'x-file-kind':kind,'x-file-name':encodeURIComponent(file.name),'x-lesson-path':selected},body:file});setNotice('Arquivo recebido por completo e vinculado à aula.');await loadDetail()}catch(error){setNotice((error as Error).message)}};
 const decision=async(checkpoint:string,decisionValue:string)=>{if(!selected||busy)return;try{await api('/decision',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessonPath:selected,checkpoint,decision:decisionValue,message:guidance})});setGuidance('');setNotice(decisionValue==='continue'?'Sua autorização foi registrada. Agora você pode avançar.':'Seu pedido de alterações foi registrado e o avanço continua bloqueado.');await loadDetail()}catch(error){setNotice((error as Error).message)}};
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><span className="brandmark">OL</span><div><strong>Academy</strong><small>Estúdio de aulas</small></div></div><button className="new" onClick={()=>setCreating(true)}>＋ Nova aula</button><div className="lessonList"><p>SUAS AULAS</p>{lessons.map(item=><button key={item.path} className={selected===item.path?'lesson active':'lesson'} onClick={()=>chooseLesson(item.path)}><span>{item.title}</span><small>{item.course} · {item.phase}</small></button>)}</div><div className="local"><i/>Executando neste notebook</div></aside>
  <section className="workspace"><header><div><p>PRODUÇÃO GUIADA</p><h1>{lesson?.title||'Crie sua primeira aula'}</h1></div><div className="progress"><span>{steps.findIndex(step=>step[0]===active)+1} de {steps.length}</span><div><i style={{width:`${((steps.findIndex(step=>step[0]===active)+1)/steps.length)*100}%`}}/></div></div></header>
   <div className="body"><nav className="steps">{steps.map(([id,label,description],index)=><button key={id} className={active===id?'current':''} onClick={()=>choose(id)}><b>{index+1}</b><span>{label}<small>{description}</small></span></button>)}</nav>
    <article className="panel">{!lesson?<Empty onCreate={()=>setCreating(true)}/>:<Step id={active} editor={editor} setEditor={setEditor} dirty={dirty} guidance={guidance} setGuidance={setGuidance} nextTopic={nextTopic} setNextTopic={setNextTopic} detail={detail} busy={busy} onRun={run} onSave={save} onUpload={upload} onDecision={decision}/>} {notice&&<div className="notice" role="status">{notice}</div>}{job&&<div className={`job ${job.status}`}><div><strong>{job.status==='running'?'Agente trabalhando…':job.status==='done'?'Etapa concluída':'Atenção necessária'}</strong><span>{job.action}</span></div>{job.output&&<details><summary>Ver detalhes</summary><pre>{job.output}</pre></details>}</div>}</article>
   </div>
  </section>{creating&&<CreateModal close={()=>setCreating(false)} done={async pathValue=>{setCreating(false);await loadLessons();setSelected(pathValue)}}/>}
 </main>
}

function Empty({onCreate}:{onCreate:()=>void}){return <div className="empty"><span>01</span><h2>Vamos transformar conhecimento em aula?</h2><p>Comece descrevendo o assunto. O estúdio conduz pesquisa, roteiro, revisões, slides, voz e vídeo.</p><button className="primary" onClick={onCreate}>Criar minha primeira aula</button></div>}
function Guidance({value,setValue,label='Orientações para o agente'}:{value:string;setValue:(value:string)=>void;label?:string}){return <label className="field guidance"><span>{label} <em>opcional</em></span><textarea value={value} onChange={event=>setValue(event.target.value)} placeholder="Escreva correções, decisões ou cuidados que devem ser respeitados nesta etapa."/></label>}
function Step({id,editor,setEditor,dirty,guidance,setGuidance,nextTopic,setNextTopic,detail,busy,onRun,onSave,onUpload,onDecision}:{id:string;editor:string;setEditor:(value:string)=>void;dirty:boolean;guidance:string;setGuidance:(value:string)=>void;nextTopic:string;setNextTopic:(value:string)=>void;detail:Detail|null;busy:boolean;onRun:(action?:string)=>void;onSave:()=>void;onUpload:(kind:string,file?:File)=>void;onDecision:(checkpoint:string,decision:string)=>void}){
 const data=steps.find(step=>step[0]===id)!;const artifact=artifactFor[id];
 if(id==='human1'||id==='human2'){const checkpoint=id==='human1'?1:2;const current=[...(detail?.decisions||[])].reverse().find(item=>item.checkpoint===checkpoint);return <><div className="eyebrow">PAUSA HUMANA {checkpoint}</div><h2>Você decide quando avançar</h2><p className="lead">Leia os materiais desta etapa. A aprovação só será registrada quando você clicar explicitamente abaixo.</p>{current&&<div className={`approval ${current.decision}`}><strong>{current.decision==='continue'?'Aprovado':'Alterações necessárias'}</strong><span>{current.automatic?'A aprovação anterior foi invalidada por uma edição posterior.':current.message||'Decisão humana registrada.'}</span></div>}<Guidance value={guidance} setValue={setGuidance} label="Comentário da revisão"/><div className="decision"><button className="primary" disabled={busy} onClick={()=>onDecision(String(checkpoint),'continue')}>Aprovar e continuar</button><button className="secondary" disabled={busy} onClick={()=>onDecision(String(checkpoint),'changes')}>Solicitar alterações</button></div></>}
 if(id==='slides')return <><div className="eyebrow">ETAPA 7 · MATERIAL VISUAL</div><h2>Envie o PowerPoint da aula</h2><p className="lead">Os slides serão a base visual obrigatória. A pesquisa oficial continua sendo a fonte técnica. O Estúdio extrai as imagens antes de chamar o analista visual.</p><Upload label="Selecionar PowerPoint" accept=".pptx" done={detail?.uploads.ppt} disabled={busy} onFile={file=>onUpload('ppt',file)}/><Guidance value={guidance} setValue={setGuidance}/><button className="primary wide" disabled={!detail?.uploads.ppt||busy} onClick={()=>onRun('slides')}>Analisar PowerPoint com o agente</button></>;
 if(id==='render')return <><div className="eyebrow">ETAPA 15 · VÍDEO FINAL</div><h2>Vincule a abertura e a conclusão</h2><p className="lead">Os uploads são concluídos de forma segura antes de substituir arquivos existentes e serão conectados automaticamente ao conteúdo da aula.</p><div className="uploadGrid"><Upload label="Vídeo de abertura" accept=".mp4,.mov,.m4v,.webm" done={detail?.uploads.opening} disabled={busy} onFile={file=>onUpload('opening',file)}/><Upload label="Vídeo de conclusão" accept=".mp4,.mov,.m4v,.webm" done={detail?.uploads.conclusion} disabled={busy} onFile={file=>onUpload('conclusion',file)}/></div><label className="field"><span>Próximo assunto</span><input value={nextTopic} onChange={event=>setNextTopic(event.target.value)} placeholder="Ex.: Camada física e meios de transmissão"/></label><button className="primary wide" disabled={busy} onClick={()=>onRun('render')}>Gerar vídeo final</button></>;
 if(id==='voiceGenerate')return <><div className="eyebrow">NARRAÇÃO</div><h2>Gerar voz da aula</h2><p className="lead">Confirme que o texto e a pronúncia já foram aprovados. A geração utilizará a voz configurada no ElevenLabs.</p><button className="primary wide" disabled={busy} onClick={()=>onRun()}>Gerar narração</button></>;
 return <><div className="eyebrow">{data[1].toUpperCase()}</div><h2>{artifact?'Revise o conteúdo desta etapa':data[2]}</h2><p className="lead">{artifact?'Edite, reescreva ou apague qualquer seção. Ao salvar, sua versão passa a ser protegida contra sobrescritas automáticas. Uma cópia anterior fica preservada para recuperação.':'O agente responsável trabalhará somente nesta etapa e apresentará o resultado para sua revisão.'}</p>{artifact&&<><textarea className="editor" value={editor} onChange={event=>setEditor(event.target.value)} placeholder="O conteúdo aparecerá aqui quando a etapa for concluída."/><span className={`saveState ${dirty?'dirty':'saved'}`}>{dirty?'Alterações ainda não salvas':'Versão salva'}</span></>}<Guidance value={guidance} setValue={setGuidance}/><div className="actions">{artifact&&<button className="secondary" disabled={!dirty||busy} onClick={onSave}>Salvar como versão oficial</button>}{id!=='brief'&&<button className="primary" disabled={busy||dirty} onClick={()=>onRun()}>{artifact&&editor?'Chamar agente novamente':'Chamar agente responsável'}</button>}</div></>;
}
function Upload({label,accept,done,disabled,onFile}:{label:string;accept:string;done?:boolean;disabled?:boolean;onFile:(file?:File)=>void}){return <label className={`upload ${done?'done':''} ${disabled?'disabled':''}`}><input type="file" accept={accept} disabled={disabled} onChange={event=>onFile(event.target.files?.[0])}/><b>{done?'✓':'↑'}</b><span>{done?'Arquivo recebido':label}<small>{done?'Você pode substituir quando quiser':'Clique para escolher no notebook'}</small></span></label>}
function CreateModal({close,done}:{close:()=>void;done:(path:string)=>void}){const [form,setForm]=useState({course:'',title:'',id:'',audience:'',objective:'',duration:'12 minutos'}),[error,setError]=useState(''),[sending,setSending]=useState(false);const submit=async()=>{setSending(true);setError('');try{const data=await api('/lessons',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});done(data.path)}catch(problem){setError((problem as Error).message);setSending(false)}};return <div className="overlay"><div className="modal"><button className="close" aria-label="Fechar" onClick={close}>×</button><div className="eyebrow">NOVA PRODUÇÃO</div><h2>Conte-nos sobre a aula</h2><div className="form"><label><span>Curso</span><input value={form.course} onChange={event=>setForm({...form,course:event.target.value})} placeholder="Ex.: Fundamentos de Redes"/></label><label><span>Título da aula</span><input value={form.title} onChange={event=>setForm({...form,title:event.target.value})} placeholder="Ex.: O modelo OSI"/></label><label><span>Identificador opcional</span><input value={form.id} onChange={event=>setForm({...form,id:event.target.value})} placeholder="Criado pelo título se vazio"/></label><label><span>Público</span><input value={form.audience} onChange={event=>setForm({...form,audience:event.target.value})} placeholder="Quem vai assistir?"/></label><label className="full"><span>O que a pessoa aprenderá?</span><textarea value={form.objective} onChange={event=>setForm({...form,objective:event.target.value})}/></label><label><span>Duração desejada</span><input value={form.duration} onChange={event=>setForm({...form,duration:event.target.value})}/></label></div>{error&&<p className="error">{error}</p>}<button className="primary wide" disabled={sending||!form.course||!form.title} onClick={submit}>{sending?'Criando…':'Criar aula e começar'}</button></div></div>}
