"use client";
import {useCallback,useEffect,useMemo,useState} from 'react';

const API='http://127.0.0.1:4318/api';
type Lesson={course:string;id:string;path:string;phase:string;title:string;state:Record<string,unknown>};
type Detail={files:Record<string,string>;state:Record<string,unknown>;videoConfig:Record<string,string>;uploads:{ppt:boolean;opening:boolean;conclusion:boolean}};
type Job={id:string;action:string;status:string;output:string};
const steps=[['brief','Definir a aula','Objetivo, público e escopo'],['direct','Planejar','Direção pedagógica'],['research','Pesquisar','Fontes oficiais e especialistas'],['script','Criar roteiro','Texto falado e segmentos'],['review1','Revisão técnica 1','Parecer independente'],['human1','Sua aprovação 1','Validar o texto antes dos slides'],['slides','Analisar PowerPoint','Upload e leitura visual'],['adapt','Adaptar aos slides','Sincronizar fala e imagem'],['storyboard','Criar storyboard','Cenas, destaques e animações'],['review2','Revisão técnica 2','Conferência após os slides'],['human2','Sua aprovação 2','Validar roteiro visual'],['voice','Preparar voz','Segmentos e pronúncia'],['voiceGenerate','Gerar narração','ElevenLabs'],['timing','Ajustar timing','Duração real do áudio'],['render','Renderizar vídeo','Remotion'],['audiovisual','Revisão audiovisual','Qualidade final']] as const;
const artifactFor:Record<string,string>={brief:'brief',research:'research',script:'script',review1:'review1',slides:'slideAnalysis',adapt:'adaptation',storyboard:'storyboard',review2:'review2',audiovisual:'qa'};
const api=async(path:string,init?:RequestInit)=>{const res=await fetch(API+path,init);const data=await res.json();if(!res.ok)throw new Error(data.error||'Não foi possível concluir');return data};

export default function Home(){
 const [lessons,setLessons]=useState<Lesson[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[active,setActive]=useState('brief'),[editor,setEditor]=useState(''),[nextTopic,setNextTopic]=useState(''),[notice,setNotice]=useState(''),[job,setJob]=useState<Job|null>(null),[creating,setCreating]=useState(false);
 const lesson=useMemo(()=>lessons.find(l=>l.path===selected),[lessons,selected]);
 const loadLessons=useCallback(async()=>{try{const d=await api('/lessons');setLessons(d.lessons);if(!selected&&d.lessons[0])setSelected(d.lessons[0].path)}catch(e){setNotice((e as Error).message)}},[selected]);
 const loadDetail=useCallback(async()=>{if(!selected)return;try{const d=await api('/lesson?path='+encodeURIComponent(selected));setDetail(d);setNextTopic(d.videoConfig.nextTopic||'');const key=artifactFor[active];setEditor(key?d.files[key]||'':'')}catch(e){setNotice((e as Error).message)}},[selected,active]);
 useEffect(()=>{loadLessons()},[loadLessons]);useEffect(()=>{loadDetail()},[loadDetail]);
 useEffect(()=>{if(!job||job.status!=='running')return;const timer=setInterval(async()=>{const d=await api('/jobs/'+job.id);setJob(d);if(d.status!=='running'){clearInterval(timer);loadDetail();loadLessons();setNotice(d.status==='done'?'Etapa concluída. Revise o resultado antes de continuar.':'A etapa terminou com erro. Veja os detalhes.') }},1500);return()=>clearInterval(timer)},[job,loadDetail,loadLessons]);
 const choose=(id:string)=>{setActive(id);const key=artifactFor[id];setEditor(key&&detail?detail.files[key]||'':'');setNotice('')};
 const run=async(action=active)=>{if(!selected)return;try{if(action==='render')await api('/video-config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessonPath:selected,nextTopic})});const d=await api('/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,lessonPath:selected,input:notice})});setJob(d);setNotice('Etapa iniciada. Você pode acompanhar o andamento abaixo.')}catch(e){setNotice((e as Error).message)}};
 const save=async()=>{const artifact=artifactFor[active];if(!artifact)return;await api('/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessonPath:selected,artifact,content:editor,note:'Revisão humana pela interface'})});setNotice('Alteração humana salva como versão oficial. Seções apagadas permanecerão removidas nas próximas etapas.');loadDetail()};
 const upload=async(kind:string,file?:File)=>{if(!file||!selected)return;setNotice(`Enviando ${file.name}...`);try{await api('/upload',{method:'POST',headers:{'x-file-kind':kind,'x-file-name':encodeURIComponent(file.name),'x-lesson-path':selected},body:file});setNotice('Arquivo recebido e vinculado à aula.');loadDetail()}catch(e){setNotice((e as Error).message)}};
 const decision=async(checkpoint:string,decision:string)=>{await api('/decision',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lessonPath:selected,checkpoint,decision,message:notice})});setNotice(decision==='continue'?'Sua autorização foi registrada. Agora você pode avançar.':'Seu pedido de alterações foi registrado.')};
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><span className="brandmark">OL</span><div><strong>Academy</strong><small>Estúdio de aulas</small></div></div><button className="new" onClick={()=>setCreating(true)}>＋ Nova aula</button><div className="lessonList"><p>SUAS AULAS</p>{lessons.map(l=><button key={l.path} className={selected===l.path?'lesson active':''} onClick={()=>{setSelected(l.path);setActive('brief')}}><span>{l.title}</span><small>{l.course} · {l.phase}</small></button>)}</div><div className="local"><i/>Executando neste notebook</div></aside>
  <section className="workspace"><header><div><p>PRODUÇÃO GUIADA</p><h1>{lesson?.title||'Crie sua primeira aula'}</h1></div><div className="progress"><span>{steps.findIndex(s=>s[0]===active)+1} de {steps.length}</span><div><i style={{width:`${((steps.findIndex(s=>s[0]===active)+1)/steps.length)*100}%`}}/></div></div></header>
   <div className="body"><nav className="steps">{steps.map(([id,label,desc],i)=><button key={id} className={active===id?'current':''} onClick={()=>choose(id)}><b>{i+1}</b><span>{label}<small>{desc}</small></span></button>)}</nav>
    <article className="panel">{!lesson?<Empty onCreate={()=>setCreating(true)}/>:<Step id={active} editor={editor} setEditor={setEditor} nextTopic={nextTopic} setNextTopic={setNextTopic} detail={detail} onRun={run} onSave={save} onUpload={upload} onDecision={decision}/>} {notice&&<div className="notice">{notice}</div>}{job&&<div className={`job ${job.status}`}><div><strong>{job.status==='running'?'Agente trabalhando…':job.status==='done'?'Etapa concluída':'Atenção necessária'}</strong><span>{job.action}</span></div>{job.output&&<details><summary>Ver detalhes</summary><pre>{job.output}</pre></details>}</div>}</article>
   </div>
  </section>{creating&&<CreateModal close={()=>setCreating(false)} done={async p=>{setCreating(false);await loadLessons();setSelected(p)}}/>}
 </main>
}

function Empty({onCreate}:{onCreate:()=>void}){return <div className="empty"><span>01</span><h2>Vamos transformar conhecimento em aula?</h2><p>Comece descrevendo o assunto. O estúdio conduz pesquisa, roteiro, revisões, slides, voz e vídeo.</p><button className="primary" onClick={onCreate}>Criar minha primeira aula</button></div>}
function Step({id,editor,setEditor,nextTopic,setNextTopic,detail,onRun,onSave,onUpload,onDecision}:{id:string;editor:string;setEditor:(s:string)=>void;nextTopic:string;setNextTopic:(s:string)=>void;detail:Detail|null;onRun:(a?:string)=>void;onSave:()=>void;onUpload:(k:string,f?:File)=>void;onDecision:(c:string,d:string)=>void}){
 const data=steps.find(s=>s[0]===id)!;const artifact=artifactFor[id];if(id==='human1'||id==='human2'){const n=id==='human1'?'1':'2';return <><div className="eyebrow">PAUSA HUMANA {n}</div><h2>Você decide quando avançar</h2><p className="lead">Leia os materiais desta etapa. A aprovação só será registrada quando você clicar explicitamente abaixo.</p><div className="decision"><button className="primary" onClick={()=>onDecision(n,'continue')}>Aprovar e continuar</button><button className="secondary" onClick={()=>onDecision(n,'changes')}>Solicitar alterações</button></div></>}
 if(id==='slides')return <><div className="eyebrow">ETAPA 7 · MATERIAL VISUAL</div><h2>Envie o PowerPoint da aula</h2><p className="lead">Os slides serão a base visual obrigatória. A pesquisa oficial continua sendo a fonte técnica.</p><Upload label="Selecionar PowerPoint" accept=".pptx" done={detail?.uploads.ppt} onFile={f=>onUpload('ppt',f)}/><button className="primary wide" disabled={!detail?.uploads.ppt} onClick={()=>onRun('slides')}>Analisar PowerPoint com o agente</button></>
 if(id==='render')return <><div className="eyebrow">ETAPA 15 · VÍDEO FINAL</div><h2>Vincule a abertura e a conclusão</h2><p className="lead">Esses vídeos serão conectados automaticamente ao conteúdo da aula.</p><div className="uploadGrid"><Upload label="Vídeo de abertura" accept="video/*" done={detail?.uploads.opening} onFile={f=>onUpload('opening',f)}/><Upload label="Vídeo de conclusão" accept="video/*" done={detail?.uploads.conclusion} onFile={f=>onUpload('conclusion',f)}/></div><label className="field"><span>Próximo assunto</span><input value={nextTopic} onChange={e=>setNextTopic(e.target.value)} placeholder="Ex.: Camada física e meios de transmissão"/></label><button className="primary wide" onClick={()=>onRun('render')}>Gerar vídeo final</button></>
 if(id==='voiceGenerate')return <><div className="eyebrow">NARRAÇÃO</div><h2>Gerar voz da aula</h2><p className="lead">Confirme que o texto e a pronúncia já foram aprovados. A geração utilizará a voz configurada no ElevenLabs.</p><button className="primary wide" onClick={()=>onRun()}>Gerar narração</button></>
 return <><div className="eyebrow">{data[1].toUpperCase()}</div><h2>{artifact?'Revise o conteúdo desta etapa':data[2]}</h2><p className="lead">{artifact?'Edite, reescreva ou apague qualquer seção. Ao salvar, sua versão passa a ser autoritativa e os agentes seguintes não poderão restaurar conteúdo removido. Uma cópia anterior fica preservada para recuperação.':'O agente responsável trabalhará somente nesta etapa e apresentará o resultado para sua revisão.'}</p>{artifact&&<textarea className="editor" value={editor} onChange={e=>setEditor(e.target.value)} placeholder="O conteúdo aparecerá aqui quando a etapa for concluída."/>}<div className="actions">{artifact&&<button className="secondary" onClick={onSave}>Salvar como versão oficial</button>}{id!=='brief'&&<button className="primary" onClick={()=>onRun()}>{artifact&&editor?'Executar novamente':'Chamar agente responsável'}</button>}</div></>
}
function Upload({label,accept,done,onFile}:{label:string;accept:string;done?:boolean;onFile:(f?:File)=>void}){return <label className={`upload ${done?'done':''}`}><input type="file" accept={accept} onChange={e=>onFile(e.target.files?.[0])}/><b>{done?'✓':'↑'}</b><span>{done?'Arquivo recebido':label}<small>{done?'Você pode substituir quando quiser':'Clique para escolher no notebook'}</small></span></label>}
function CreateModal({close,done}:{close:()=>void;done:(p:string)=>void}){const [form,setForm]=useState({course:'',title:'',id:'',audience:'',objective:'',duration:'12 minutos'}),[error,setError]=useState('');const submit=async()=>{try{const d=await api('/lessons',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});done(d.path)}catch(e){setError((e as Error).message)}};return <div className="overlay"><div className="modal"><button className="close" onClick={close}>×</button><div className="eyebrow">NOVA PRODUÇÃO</div><h2>Conte-nos sobre a aula</h2><div className="form"><label><span>Curso</span><input value={form.course} onChange={e=>setForm({...form,course:e.target.value})} placeholder="Ex.: Fundamentos de Redes"/></label><label><span>Título da aula</span><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: O modelo OSI"/></label><label><span>Identificador opcional</span><input value={form.id} onChange={e=>setForm({...form,id:e.target.value})} placeholder="Criado pelo título se vazio"/></label><label><span>Público</span><input value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})} placeholder="Quem vai assistir?"/></label><label className="full"><span>O que a pessoa aprenderá?</span><textarea value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}/></label><label><span>Duração desejada</span><input value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label></div>{error&&<p className="error">{error}</p>}<button className="primary wide" onClick={submit}>Criar aula e começar</button></div></div>}
