import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import crypto from 'node:crypto';

const ROOT=path.resolve(import.meta.dirname,'../..');
const PORT=Number(process.env.OLACADEMY_API_PORT||4318);
const jobs=new Map();
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*'});res.end(JSON.stringify(data))};
const body=async(req)=>{const chunks=[];for await(const chunk of req)chunks.push(chunk);return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')};
const safeLesson=(value)=>{const full=path.resolve(ROOT,String(value||''));const base=path.join(ROOT,'courses')+path.sep;if(!full.startsWith(base)||!full.includes(`${path.sep}lessons${path.sep}`))throw new Error('Pasta de aula inválida');return full};
const rel=(p)=>path.relative(ROOT,p);
const slug=(value)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const readJson=(file,fallback={})=>{try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}};
const listLessons=()=>{const courses=path.join(ROOT,'courses');const out=[];if(!fs.existsSync(courses))return out;for(const course of fs.readdirSync(courses)){const lessons=path.join(courses,course,'lessons');if(!fs.existsSync(lessons))continue;for(const id of fs.readdirSync(lessons)){const dir=path.join(lessons,id);if(!fs.statSync(dir).isDirectory())continue;const state=readJson(path.join(dir,'workflow-state.json'));const brief=fs.existsSync(path.join(dir,'lesson-brief.md'))?fs.readFileSync(path.join(dir,'lesson-brief.md'),'utf8'):'';out.push({course,id,path:rel(dir),phase:state.phase||'BRIEF',title:brief.match(/- Tema:\s*(.+)/)?.[1]||id,state})}}return out};
const artifacts=[
  ['brief','lesson-brief.md'],['research','research/research.md'],['script','script/lesson-script.md'],['review1','qa/technical-review-1.md'],['slideAnalysis','source/slide-analysis.md'],['adaptation','script/slide-adaptation.md'],['storyboard','storyboard/scene-plan.json'],['review2','qa/technical-review-2.md'],['qa','qa/audiovisual-review.md']
];
const lessonDetail=(dir)=>{const videoConfig=readJson(path.join(dir,'video-config.json'));const configured=(key)=>{if(!videoConfig[key])return false;const value=String(videoConfig[key]);return fs.existsSync(path.resolve(dir,value))||fs.existsSync(path.resolve(ROOT,value))};return {files:Object.fromEntries(artifacts.map(([key,file])=>[key,fs.existsSync(path.join(dir,file))?fs.readFileSync(path.join(dir,file),'utf8'):''])),state:readJson(path.join(dir,'workflow-state.json')),videoConfig,uploads:{ppt:fs.existsSync(path.join(dir,'source/original/deck.pptx')),opening:configured('openingVideo'),conclusion:configured('conclusionVideo')}}};

const agentActions={
  direct:{agent:'course-director',prompt:'Leia o lesson-brief.md desta aula, refine o plano de produção e grave o resultado em production-plan.md. Não avance para pesquisa.'},
  research:{agent:'official-docs-researcher',prompt:'Execute a pesquisa técnica desta aula usando fontes primárias/oficiais. Grave os artefatos na pasta research/ e respeite o escopo do lesson-brief.md.'},
  script:{agent:'instructional-scriptwriter',prompt:'Crie ou revise o roteiro falado e os segmentos da aula com base no brief e na pesquisa. Inclua SEG-000 exatamente conforme brain/opening-signature.md. Grave os artefatos nas pastas script/ e voice/.'},
  slides:{agent:'powerpoint-visual-analyst',prompt:'Analise obrigatoriamente o PowerPoint em source/original/deck.pptx como insumo visual. Grave source/slide-analysis.md e os demais artefatos de ingestão necessários, sem tratar o PPT como fonte técnica.'},
  adapt:{agent:'instructional-scriptwriter',prompt:'Adapte o roteiro aos slides aprovados. Atualize script/slide-adaptation.md, script/slide-map.json e os textos necessários sem alterar fatos técnicos validados.'},
  storyboard:{agent:'visual-director',prompt:'Crie ou refine o storyboard inicial desta aula usando o roteiro adaptado e todos os slides. Grave storyboard/scene-plan.json.'},
  voice:{agent:'voice-director',prompt:'Prepare e valide os segmentos finais para voz, pronúncia e direção vocal. Não gere áudio sem as credenciais configuradas.'},
  timing:{agent:'visual-director',prompt:'Ajuste o timing final do storyboard usando as durações reais de áudio e preserve todos os slides obrigatórios.'},
  audiovisual:{agent:'audiovisual-qa',prompt:'Revise o vídeo final, áudio, sincronização, legibilidade e conformidade visual. Grave qa/audiovisual-review.md.'}
};
const codexActions={review1:'Faça a revisão técnica independente #1 desta aula. Use fontes oficiais como verdade e grave o parecer em qa/technical-review-1.md. Não implemente correções.',review2:'Faça a revisão técnica independente #2 do roteiro adaptado, slides e storyboard. Grave o parecer em qa/technical-review-2.md. Não implemente correções.'};
const commands={ingest:['npm','run','slides:ingest','--'],voiceGenerate:['npm','run','voice:generate','--'],storyboardAuto:['npm','run','storyboard:auto','--'],render:['npm','run','video:render','--'],validate:['npm','run','video:validate']};
const humanAuthority=(lesson)=>{const file=path.join(lesson,'qa','human-edits.json');if(!fs.existsSync(file))return '';return '\n\nREGRA OBRIGATÓRIA: existem alterações humanas registradas em qa/human-edits.json. O conteúdo atual dos artefatos da aula é autoritativo. Preserve inclusões, reformulações e exclusões feitas pela pessoa revisora. Não restaure seções removidas e não reverta decisões humanas, salvo se a observação humana desta execução pedir isso expressamente.'};
const startJob=(action,lessonPath,input='')=>{const id=crypto.randomUUID();const job={id,action,status:'running',output:'',startedAt:new Date().toISOString()};const lesson=safeLesson(lessonPath);const decisions=readJson(path.join(lesson,'qa','human-decisions.json'),{decisions:[]}).decisions||[];const approved=(checkpoint)=>[...decisions].reverse().find(d=>d.checkpoint===checkpoint)?.decision==='continue';if(['slides','adapt','storyboard','review2'].includes(action)&&!approved(1))throw new Error('Aprovação humana 1 necessária antes desta etapa');if(['voice','voiceGenerate','timing','render','audiovisual'].includes(action)&&!approved(2))throw new Error('Aprovação humana 2 necessária antes desta etapa');jobs.set(id,job);let command,args;
  if(agentActions[action]){const spec=agentActions[action];command='claude';args=['-p','--agent',spec.agent,'--permission-mode','acceptEdits',`${spec.prompt}\n\nAula: ${rel(lesson)}\nObservação humana: ${input||'nenhuma'}${humanAuthority(lesson)}`]}
  else if(codexActions[action]){command='codex';args=['exec','-C',ROOT,'-s','workspace-write','-a','never',`${codexActions[action]}\n\nAula: ${rel(lesson)}\nObservação humana: ${input||'nenhuma'}${humanAuthority(lesson)}`]}
  else if(commands[action]){[command,...args]=commands[action];if(action!=='validate')args.push(rel(lesson));}
  else throw new Error('Ação desconhecida');
  const child=spawn(command,args,{cwd:ROOT,env:process.env});job.pid=child.pid;child.stdout.on('data',d=>job.output+=d);child.stderr.on('data',d=>job.output+=d);child.on('error',e=>{job.status='error';job.output+=`\n${e.message}`});child.on('close',code=>{job.status=code===0?'done':'error';job.code=code;job.finishedAt=new Date().toISOString()});return job;
};

const server=http.createServer(async(req,res)=>{try{
  if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-file-name,x-file-kind,x-lesson-path'});return res.end()}
  const url=new URL(req.url||'/',`http://${req.headers.host}`);
  if(req.method==='GET'&&url.pathname==='/api/health')return json(res,200,{ok:true,root:ROOT});
  if(req.method==='GET'&&url.pathname==='/api/lessons')return json(res,200,{lessons:listLessons()});
  if(req.method==='GET'&&url.pathname==='/api/lesson')return json(res,200,lessonDetail(safeLesson(url.searchParams.get('path'))));
  if(req.method==='GET'&&url.pathname.startsWith('/api/jobs/'))return json(res,200,jobs.get(url.pathname.split('/').pop())||{status:'missing'});
  if(req.method==='POST'&&url.pathname==='/api/lessons'){const data=await body(req);const course=slug(data.course);const id=slug(data.id||data.title);if(!course||!id||!data.title)throw new Error('Informe curso, título e identificador');const dir=safeLesson(path.join('courses',course,'lessons',id));if(fs.existsSync(dir))throw new Error('Essa aula já existe');for(const d of ['research','script','voice/generated','source/input','source/original','source/slides','source/extracted-media','storyboard','visuals','qa'])fs.mkdirSync(path.join(dir,d),{recursive:true});const brief=`# Lesson Brief\n\n- Lesson ID: ${id}\n- Tema: ${data.title}\n- Curso: ${course}\n- Público: ${data.audience||''}\n- Pré-requisitos: ${data.prerequisites||''}\n- Objetivo de aprendizagem: ${data.objective||''}\n- Duração alvo: ${data.duration||''}\n- Escopo incluído: ${data.scope||''}\n- Fora de escopo: ${data.outOfScope||''}\n`;fs.writeFileSync(path.join(dir,'lesson-brief.md'),brief);fs.writeFileSync(path.join(dir,'workflow-state.json'),JSON.stringify({lessonId:id,phase:'BRIEF',humanCheckpoint:null},null,2));return json(res,201,{path:rel(dir)})}
  if(req.method==='POST'&&url.pathname==='/api/save'){const data=await body(req);const dir=safeLesson(data.lessonPath);const allowed=new Map(artifacts.map(([key,file])=>[key,file]));const file=allowed.get(data.artifact);if(!file)throw new Error('Artefato não editável');const target=path.join(dir,file);const previous=fs.existsSync(target)?fs.readFileSync(target,'utf8'):'';const content=String(data.content||'');fs.mkdirSync(path.dirname(target),{recursive:true});if(previous!==content){const stamp=new Date().toISOString().replace(/[:.]/g,'-');const historyDir=path.join(dir,'qa','human-edits');fs.mkdirSync(historyDir,{recursive:true});fs.writeFileSync(path.join(historyDir,`${stamp}-${data.artifact}-anterior.md`),previous);const ledgerFile=path.join(dir,'qa','human-edits.json');const ledger=readJson(ledgerFile,{policy:'Alterações humanas são autoritativas. Seções removidas não podem ser restauradas automaticamente.',edits:[]});ledger.edits.push({artifact:data.artifact,file,at:new Date().toISOString(),action:previous?'edited':'created',note:String(data.note||'Edição feita no Estúdio OL Academy')});fs.writeFileSync(ledgerFile,JSON.stringify(ledger,null,2));fs.writeFileSync(target,content)}return json(res,200,{ok:true,changed:previous!==content})}
  if(req.method==='POST'&&url.pathname==='/api/decision'){const data=await body(req);if(!['1','2'].includes(String(data.checkpoint))||!['continue','changes'].includes(data.decision))throw new Error('Decisão inválida');const dir=safeLesson(data.lessonPath);const file=path.join(dir,'qa','human-decisions.json');const current=readJson(file,{decisions:[]});current.decisions.push({checkpoint:Number(data.checkpoint),decision:data.decision,message:data.message||'',at:new Date().toISOString()});fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(current,null,2));return json(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/video-config'){const data=await body(req);const dir=safeLesson(data.lessonPath);const file=path.join(dir,'video-config.json');const value=readJson(file);value.nextTopic=String(data.nextTopic||'').trim();fs.writeFileSync(file,JSON.stringify(value,null,2));return json(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/run'){const data=await body(req);return json(res,202,startJob(data.action,data.lessonPath,data.input))}
  if(req.method==='POST'&&url.pathname==='/api/upload'){const lesson=safeLesson(req.headers['x-lesson-path']);const kind=String(req.headers['x-file-kind']||'');const original=path.basename(decodeURIComponent(String(req.headers['x-file-name']||'arquivo')));let target;if(kind==='ppt')target=path.join(lesson,'source/original/deck.pptx');else if(kind==='opening')target=path.join(ROOT,'assets/video/opening'+(path.extname(original)||'.mp4'));else if(kind==='conclusion')target=path.join(ROOT,'assets/video/conclusion'+(path.extname(original)||'.mp4'));else throw new Error('Tipo de upload inválido');fs.mkdirSync(path.dirname(target),{recursive:true});const stream=fs.createWriteStream(target,{flags:'w'});req.pipe(stream);await new Promise((resolve,reject)=>{stream.on('finish',resolve);stream.on('error',reject)});if(kind!=='ppt'){const cfg=path.join(lesson,'video-config.json');const value=readJson(cfg);value[kind==='opening'?'openingVideo':'conclusionVideo']=rel(target);fs.writeFileSync(cfg,JSON.stringify(value,null,2))}return json(res,201,{ok:true,file:rel(target)})}
  return json(res,404,{error:'Rota não encontrada'});
 }catch(error){return json(res,400,{error:error instanceof Error?error.message:String(error)})}});
server.listen(PORT,'127.0.0.1',()=>console.log(`OLacademy API: http://127.0.0.1:${PORT}`));
