import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import crypto from 'node:crypto';
import {once} from 'node:events';

const ROOT=path.resolve(import.meta.dirname,'../..');
const PORT=Number(process.env.OLACADEMY_API_PORT||4318);
const MAX_UPLOAD_BYTES=2*1024*1024*1024;
const MAX_JOB_OUTPUT=2*1024*1024;
const ALLOWED_ORIGINS=new Set(['http://localhost:3000','http://127.0.0.1:3000']);
const VIDEO_DEFAULTS_FILE=path.join(ROOT,'config','video-defaults.json');
const jobs=new Map();

const requestOrigin=(req)=>String(req.headers.origin||'');
const corsHeaders=(req)=>{const origin=requestOrigin(req);return {'access-control-allow-origin':origin&&ALLOWED_ORIGINS.has(origin)?origin:'http://localhost:3000','vary':'Origin'}};
const json=(req,res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8',...corsHeaders(req)});res.end(JSON.stringify(data))};
const body=async(req)=>{const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>2*1024*1024)throw new Error('Dados enviados excedem o limite permitido');chunks.push(chunk)}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')};
const readJson=(file,fallback={})=>{try{return JSON.parse(fs.readFileSync(file,'utf8'))}catch{return fallback}};
const writeJsonAtomic=(file,value)=>{fs.mkdirSync(path.dirname(file),{recursive:true});const temp=`${file}.tmp-${crypto.randomUUID()}`;fs.writeFileSync(temp,JSON.stringify(value,null,2));fs.renameSync(temp,file)};
const rel=(p)=>path.relative(ROOT,p);
const slug=(value)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const safeLesson=(value)=>{const full=path.resolve(ROOT,String(value||''));const base=path.join(ROOT,'courses')+path.sep;if(!full.startsWith(base)||!full.includes(`${path.sep}lessons${path.sep}`))throw new Error('Pasta de aula inválida');return full};
const ensureLocalRequest=(req)=>{const origin=requestOrigin(req);if(origin&&!ALLOWED_ORIGINS.has(origin))throw new Error('Origem não autorizada a controlar o Estúdio')};

const artifacts=[
  ['brief','lesson-brief.md'],['research','research/research.md'],['script','script/lesson-script.md'],['review1','qa/technical-review-1.md'],['slideAnalysis','source/slide-analysis.md'],['adaptation','script/slide-adaptation.md'],['storyboard','storyboard/scene-plan.json'],['review2','qa/technical-review-2.md'],['qa','qa/audiovisual-review.md']
];
const artifactMap=new Map(artifacts);
const listLessons=()=>{const courses=path.join(ROOT,'courses');const out=[];if(!fs.existsSync(courses))return out;for(const course of fs.readdirSync(courses)){const lessons=path.join(courses,course,'lessons');if(!fs.existsSync(lessons))continue;for(const id of fs.readdirSync(lessons)){const dir=path.join(lessons,id);if(!fs.statSync(dir).isDirectory())continue;const state=readJson(path.join(dir,'workflow-state.json'));const brief=fs.existsSync(path.join(dir,'lesson-brief.md'))?fs.readFileSync(path.join(dir,'lesson-brief.md'),'utf8'):'';out.push({course,id,path:rel(dir),phase:state.phase||'BRIEF',title:brief.match(/- Tema:\s*(.+)/)?.[1]||id,state})} }return out};
const decisionsFor=(lesson)=>readJson(path.join(lesson,'qa','human-decisions.json'),{decisions:[]}).decisions||[];
const latestDecision=(lesson,checkpoint)=>[...decisionsFor(lesson)].reverse().find(d=>d.checkpoint===checkpoint)?.decision;
const videoDefaults=()=>readJson(VIDEO_DEFAULTS_FILE,{});
const configuredDefault=(key)=>{const value=videoDefaults()[key];return Boolean(value&&fs.existsSync(path.resolve(ROOT,String(value))))};
const defaultsDetail=()=>({config:videoDefaults(),uploads:{opening:configuredDefault('openingVideo'),conclusion:configuredDefault('conclusionVideo')}});
const lessonDetail=(dir)=>{const videoConfig=readJson(path.join(dir,'video-config.json'));const configured=(key)=>{if(!videoConfig[key])return false;const value=String(videoConfig[key]);return fs.existsSync(path.resolve(dir,value))||fs.existsSync(path.resolve(ROOT,value))};return {files:Object.fromEntries(artifacts.map(([key,file])=>[key,fs.existsSync(path.join(dir,file))?fs.readFileSync(path.join(dir,file),'utf8'):''])),state:readJson(path.join(dir,'workflow-state.json')),videoConfig,decisions:decisionsFor(dir),uploads:{ppt:fs.existsSync(path.join(dir,'source/original/deck.pptx')),opening:configured('openingVideo'),conclusion:configured('conclusionVideo')}}};

const agentActions={
  direct:{agent:'course-director',prompt:'Leia o lesson-brief.md desta aula, refine o plano de produção e grave o resultado em production-plan.md. Não avance para pesquisa.'},
  research:{agent:'official-docs-researcher',prompt:'Execute a pesquisa técnica desta aula usando fontes primárias/oficiais. Grave os artefatos na pasta research/ e respeite o escopo do lesson-brief.md.'},
  script:{agent:'instructional-scriptwriter',prompt:'Crie ou revise o roteiro falado e os segmentos da aula com base no brief e na pesquisa. Inclua SEG-000 exatamente conforme brain/opening-signature.md. Grave os artefatos nas pastas script/ e voice/.'},
  slides:{agent:'powerpoint-visual-analyst',prompt:'Analise obrigatoriamente o PowerPoint em source/original/deck.pptx e as imagens extraídas como insumo visual. Grave source/slide-analysis.md, sem tratar o PPT como fonte técnica.'},
  adapt:{agent:'instructional-scriptwriter',prompt:'Adapte o roteiro aos slides aprovados. Atualize script/slide-adaptation.md, script/slide-map.json e os textos necessários sem alterar fatos técnicos ou decisões humanas validadas.'},
  storyboard:{agent:'visual-director',prompt:'Crie ou refine o storyboard inicial desta aula usando o roteiro adaptado e todos os slides. Grave storyboard/scene-plan.json.'},
  voice:{agent:'voice-director',prompt:'Prepare e valide os segmentos finais para voz, pronúncia e direção vocal. Não gere áudio sem as credenciais configuradas.'},
  timing:{agent:'visual-director',prompt:'Ajuste o timing final do storyboard usando as durações reais de áudio e preserve todos os slides obrigatórios.'},
  audiovisual:{agent:'audiovisual-qa',prompt:'Revise o vídeo final, áudio, sincronização, legibilidade e conformidade visual. Grave qa/audiovisual-review.md.'}
};
const codexActions={review1:'Faça a revisão técnica independente #1 desta aula. Use fontes oficiais como verdade e grave o parecer em qa/technical-review-1.md. Não implemente correções.',review2:'Faça a revisão técnica independente #2 do roteiro adaptado, slides e storyboard. Grave o parecer em qa/technical-review-2.md. Não implemente correções.'};
const commands={voiceGenerate:['npm','run','voice:generate','--'],storyboardAuto:['npm','run','storyboard:auto','--'],render:['npm','run','video:render','--'],validate:['npm','run','video:validate']};
const humanLedger=(lesson)=>readJson(path.join(lesson,'qa','human-edits.json'),{edits:[]});
const humanAuthority=(lesson)=>humanLedger(lesson).edits?.length?'\n\nREGRA OBRIGATÓRIA: existem alterações humanas registradas em qa/human-edits.json. O conteúdo atual dos artefatos da aula é autoritativo. Preserve inclusões, reformulações e exclusões feitas pela pessoa revisora. Não restaure seções removidas e não reverta decisões humanas. Arquivos editados pela pessoa revisora são protegidos e qualquer sobrescrita automática será descartada.':'';
const protectedSnapshots=(lesson)=>{const snapshots=new Map();const ledgerFile=path.join(lesson,'qa','human-edits.json');if(fs.existsSync(ledgerFile))snapshots.set(ledgerFile,fs.readFileSync(ledgerFile));for(const edit of humanLedger(lesson).edits||[]){const file=path.resolve(lesson,String(edit.file||''));if(file.startsWith(lesson+path.sep)&&fs.existsSync(file))snapshots.set(file,fs.readFileSync(file))}return snapshots};
const restoreProtected=(snapshots)=>{const restored=[];for(const [file,content] of snapshots){if(!fs.existsSync(file)||!fs.readFileSync(file).equals(content)){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,content);restored.push(path.basename(file))}}return restored};
const agentCommand=(spec,lesson,input)=>['claude',['-p','--agent',spec.agent,'--permission-mode','acceptEdits',`${spec.prompt}\n\nAula: ${rel(lesson)}\nOrientação humana: ${input||'nenhuma'}${humanAuthority(lesson)}`]];
const codexCommand=(prompt,lesson,input)=>['codex',['exec','-C',ROOT,'-s','workspace-write','-a','never',`${prompt}\n\nAula: ${rel(lesson)}\nOrientação humana: ${input||'nenhuma'}${humanAuthority(lesson)}`]];
const commandSequence=(action,lesson,input)=>{
  if(action==='slides')return [['npm',['run','slides:ingest','--',rel(lesson)]],agentCommand(agentActions.slides,lesson,input)];
  if(agentActions[action])return [agentCommand(agentActions[action],lesson,input)];
  if(codexActions[action])return [codexCommand(codexActions[action],lesson,input)];
  if(commands[action]){const [command,...args]=commands[action];if(action!=='validate')args.push(rel(lesson));return [[command,args]]}
  throw new Error('Ação desconhecida');
};
const appendOutput=(job,value)=>{job.output=(job.output+value).slice(-MAX_JOB_OUTPUT)};
const startJob=(action,lessonPath,input='')=>{const lesson=safeLesson(lessonPath);if([...jobs.values()].some(j=>j.lessonPath===rel(lesson)&&j.status==='running'))throw new Error('Já existe uma etapa em execução para esta aula');if(['slides','adapt','storyboard','review2'].includes(action)&&latestDecision(lesson,1)!=='continue')throw new Error('Aprovação humana 1 necessária antes desta etapa');if(['voice','voiceGenerate','timing','render','audiovisual'].includes(action)&&latestDecision(lesson,2)!=='continue')throw new Error('Aprovação humana 2 necessária antes desta etapa');if(action==='slides'&&!fs.existsSync(path.join(lesson,'source/original/deck.pptx')))throw new Error('Envie o PowerPoint antes de iniciar a análise');if(action==='render'&&(!configuredDefault('openingVideo')||!configuredDefault('conclusionVideo')))throw new Error('Envie os vídeos padrão de abertura e conclusão antes de renderizar');if(action==='render'){const videoConfig=readJson(path.join(lesson,'video-config.json'));if(!String(videoConfig.openingTitle||'').trim())throw new Error('Informe o título exibido na abertura');if(!String(videoConfig.nextTopic||'').trim())throw new Error('Informe a próxima aula para personalizar o vídeo de encerramento')}
  const id=crypto.randomUUID();const job={id,action,lessonPath:rel(lesson),status:'running',output:'',startedAt:new Date().toISOString()};const sequence=commandSequence(action,lesson,String(input||''));const snapshots=protectedSnapshots(lesson);jobs.set(id,job);
  const runAt=(index)=>{if(index>=sequence.length){const restored=restoreProtected(snapshots);if(restored.length)appendOutput(job,`\nProteção humana: alterações automáticas descartadas em ${restored.join(', ')}.\n`);job.status='done';job.finishedAt=new Date().toISOString();return}const [command,args]=sequence[index];appendOutput(job,`\n▶ ${index+1}/${sequence.length}: ${action}\n`);const child=spawn(command,args,{cwd:ROOT,env:process.env});job.pid=child.pid;child.stdout.on('data',d=>appendOutput(job,d));child.stderr.on('data',d=>appendOutput(job,d));child.on('error',e=>{restoreProtected(snapshots);job.status='error';appendOutput(job,`\n${e.message}`);job.finishedAt=new Date().toISOString()});child.on('close',code=>{if(job.status==='error')return;if(code!==0){restoreProtected(snapshots);job.status='error';job.code=code;job.finishedAt=new Date().toISOString();return}runAt(index+1)})};runAt(0);return job;
};

const receiveUpload=async(req,target)=>{const declared=Number(req.headers['content-length']||0);if(declared>MAX_UPLOAD_BYTES)throw new Error('O arquivo excede o limite de 2 GB');fs.mkdirSync(path.dirname(target),{recursive:true});const temp=`${target}.uploading-${crypto.randomUUID()}`;const stream=fs.createWriteStream(temp,{flags:'wx'});let size=0;try{for await(const chunk of req){size+=chunk.length;if(size>MAX_UPLOAD_BYTES)throw new Error('O arquivo excede o limite de 2 GB');if(!stream.write(chunk))await once(stream,'drain')}stream.end();await once(stream,'finish');fs.renameSync(temp,target)}catch(error){stream.destroy();if(fs.existsSync(temp))fs.unlinkSync(temp);throw error}};
const validateDecision=(lesson,checkpoint)=>{const required=checkpoint===1?['script/lesson-script.md','qa/technical-review-1.md']:['source/slide-analysis.md','script/slide-adaptation.md','storyboard/scene-plan.json','qa/technical-review-2.md'];const missing=required.filter(file=>!fs.existsSync(path.join(lesson,file))||fs.statSync(path.join(lesson,file)).size===0);if(missing.length)throw new Error(`Ainda faltam materiais para aprovar: ${missing.join(', ')}`)};
const invalidateApproval=(lesson,artifact)=>{const checkpoint=['brief','research','script','review1'].includes(artifact)?1:['slideAnalysis','adaptation','storyboard','review2'].includes(artifact)?2:null;if(!checkpoint||latestDecision(lesson,checkpoint)!=='continue')return;const file=path.join(lesson,'qa','human-decisions.json');const current=readJson(file,{decisions:[]});current.decisions.push({checkpoint,decision:'changes',message:`Aprovação invalidada por edição humana posterior em ${artifact}.`,at:new Date().toISOString(),automatic:true});writeJsonAtomic(file,current)};

const server=http.createServer(async(req,res)=>{try{
  ensureLocalRequest(req);
  if(req.method==='OPTIONS'){res.writeHead(204,{...corsHeaders(req),'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-file-name,x-file-kind,x-lesson-path'});return res.end()}
  const url=new URL(req.url||'/',`http://${req.headers.host}`);
  if(req.method==='GET'&&url.pathname==='/api/health')return json(req,res,200,{ok:true,root:ROOT});
  if(req.method==='GET'&&url.pathname==='/api/lessons')return json(req,res,200,{lessons:listLessons()});
  if(req.method==='GET'&&url.pathname==='/api/settings')return json(req,res,200,defaultsDetail());
  if(req.method==='GET'&&url.pathname==='/api/lesson')return json(req,res,200,lessonDetail(safeLesson(url.searchParams.get('path'))));
  if(req.method==='GET'&&url.pathname.startsWith('/api/jobs/'))return json(req,res,200,jobs.get(url.pathname.split('/').pop())||{status:'missing'});
  if(req.method==='POST'&&url.pathname==='/api/lessons'){const data=await body(req);const course=slug(data.course);const id=slug(data.id||data.title);const title=String(data.title||'').trim();const nextTopic=String(data.nextTopic||'').trim();if(!course||!id||!title)throw new Error('Informe curso e título');if(!nextTopic)throw new Error('Informe qual será a próxima aula');const dir=safeLesson(path.join('courses',course,'lessons',id));if(fs.existsSync(dir))throw new Error('Essa aula já existe');for(const d of ['research','script','voice/generated','source/input','source/original','source/slides','source/extracted-media','storyboard','visuals','qa'])fs.mkdirSync(path.join(dir,d),{recursive:true});const brief=`# Lesson Brief\n\n- Lesson ID: ${id}\n- Tema: ${title}\n- Curso: ${course}\n- Público: ${data.audience||''}\n- Pré-requisitos: ${data.prerequisites||''}\n- Objetivo de aprendizagem: ${data.objective||''}\n- Duração alvo: ${data.duration||''}\n- Escopo incluído: ${data.scope||''}\n- Fora de escopo: ${data.outOfScope||''}\n`;fs.writeFileSync(path.join(dir,'lesson-brief.md'),brief);writeJsonAtomic(path.join(dir,'video-config.json'),{openingTitle:title,nextTopic});writeJsonAtomic(path.join(dir,'workflow-state.json'),{lessonId:id,phase:'BRIEF',humanCheckpoint:null});return json(req,res,201,{path:rel(dir)})}
  if(req.method==='POST'&&url.pathname==='/api/save'){const data=await body(req);const dir=safeLesson(data.lessonPath);const file=artifactMap.get(data.artifact);if(!file)throw new Error('Artefato não editável');const target=path.join(dir,file);const existed=fs.existsSync(target);const previous=existed?fs.readFileSync(target,'utf8'):'';const content=String(data.content??'');if(previous!==content){const stamp=new Date().toISOString().replace(/[:.]/g,'-');const historyDir=path.join(dir,'qa','human-edits');fs.mkdirSync(historyDir,{recursive:true});if(existed)fs.writeFileSync(path.join(historyDir,`${stamp}-${data.artifact}-anterior.md`),previous);const ledgerFile=path.join(dir,'qa','human-edits.json');const ledger=humanLedger(dir);ledger.policy='Alterações humanas são autoritativas. Seções removidas não podem ser restauradas automaticamente.';ledger.edits=ledger.edits||[];ledger.edits.push({artifact:data.artifact,file,at:new Date().toISOString(),action:existed?'edited':'created',note:String(data.note||'Edição feita no Estúdio OL Academy')});writeJsonAtomic(ledgerFile,ledger);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content);invalidateApproval(dir,data.artifact)}return json(req,res,200,{ok:true,changed:previous!==content})}
  if(req.method==='POST'&&url.pathname==='/api/decision'){const data=await body(req);const checkpoint=Number(data.checkpoint);if(![1,2].includes(checkpoint)||!['continue','changes'].includes(data.decision))throw new Error('Decisão inválida');const dir=safeLesson(data.lessonPath);if(data.decision==='continue')validateDecision(dir,checkpoint);const file=path.join(dir,'qa','human-decisions.json');const current=readJson(file,{decisions:[]});current.decisions.push({checkpoint,decision:data.decision,message:String(data.message||''),at:new Date().toISOString()});writeJsonAtomic(file,current);return json(req,res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/video-config'){const data=await body(req);const dir=safeLesson(data.lessonPath);const file=path.join(dir,'video-config.json');const openingTitle=String(data.openingTitle||'').trim();const nextTopic=String(data.nextTopic||'').trim();if(!openingTitle)throw new Error('Informe o título exibido na abertura');if(!nextTopic)throw new Error('Informe a próxima aula para personalizar o vídeo de encerramento');const value=readJson(file);value.openingTitle=openingTitle;value.nextTopic=nextTopic;writeJsonAtomic(file,value);return json(req,res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/run'){const data=await body(req);return json(req,res,202,startJob(data.action,data.lessonPath,data.input))}
  if(req.method==='POST'&&url.pathname==='/api/upload'){const kind=String(req.headers['x-file-kind']||'');const original=path.basename(decodeURIComponent(String(req.headers['x-file-name']||'arquivo')));const ext=path.extname(original).toLowerCase();if(['defaultOpening','defaultConclusion'].includes(kind)){if(!['.mp4','.mov','.m4v','.webm'].includes(ext))throw new Error('Formato de vídeo não suportado. Use MP4, MOV, M4V ou WebM');const name=kind==='defaultOpening'?'default-opening':'default-conclusion';const target=path.join(ROOT,'assets','video',name+ext);await receiveUpload(req,target);const defaults=videoDefaults();defaults[kind==='defaultOpening'?'openingVideo':'conclusionVideo']=rel(target);writeJsonAtomic(VIDEO_DEFAULTS_FILE,defaults);return json(req,res,201,{ok:true,file:rel(target)})}const lesson=safeLesson(req.headers['x-lesson-path']);if(kind!=='ppt')throw new Error('Tipo de upload inválido');if(ext!=='.pptx')throw new Error('Selecione um arquivo PowerPoint .pptx');const target=path.join(lesson,'source/original/deck.pptx');await receiveUpload(req,target);invalidateApproval(lesson,'slideAnalysis');return json(req,res,201,{ok:true,file:rel(target)})}
  return json(req,res,404,{error:'Rota não encontrada'});
 }catch(error){return json(req,res,400,{error:error instanceof Error?error.message:String(error)})}});
server.listen(PORT,'127.0.0.1',()=>console.log(`OLacademy API: http://127.0.0.1:${PORT}`));
